### ISSUE TITLE
support for plugins

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer-styl#1]
I implemented it in `jstransformer-rework` and `jstransformer-postcss` as "locals" but wasn't good idea. Maybe it would be better to be object with property `plugins` or `use`

**fixture.css**

``` styl
:root
  --redpie: red

div
  background: var(--redpie)
  color: var(--other-color, green)
  top: divide(subtract(30, floor(multiply(20, 10))), 2)
```

transform using styl + plus whitespace + vars plugin + plugin for functions

``` js
var plugins = [
  require('rework-plugin-function')({
    subtract: function(a, b) { return a - b },
    multiply: function(a, b) { return a * b },
    divide: function(a, b) { return a / b },
    floor: Math.floor
  }),
  require('rework-vars')()
];
transform.renderFile('./fixture.css', {whitespace: true}, {plugins: plugins});
```

**Comment by tunnckoCore** [comment]
face the problem with that locals to be array, while refactoring `metalsmith-jstransformer`.

**Comment by TimothyGu** [comment]
Sounds good.

**Comment by TimothyGu** [comment]
Also note that this is exactly how jstransformer-stylus works.
